### ISSUE TITLE
easy to find devices porting status

### ISSUE THREAD

**Issue by lduboeuf** [Halium/docs#136]
hi,
Many users would like to know if their device is ported or what are the current status.
When coming from https://devices.ubuntu-touch.io/ or halium.org or halium doc, it is not so easy to find the link https://github.com/Halium/projectmanagement/issues
Nevertheless, it is maybe the first question of people interested in UT.
I think we should do something about it

**Comment by UniversalSuperBox** [comment]
Hi @lduboeuf,

Halium as a project is not specific to Ubuntu Touch, so this Halium repository is not an appropriate place to discuss this issue for that project

Coming from the Halium community side, I'm not really sure I'd like to publicise all of the in-progress porting efforts. Some of them are in very early stages or are not being worked on, and I'm not sure if people asking "can you finish this already?" will be helpful. In my opinion, there are already enough testers out there for Android modding, what's needed are people who can help porting.

From the practical side, there is a table of devices along with their status here: http://docs.halium.org/en/latest/supplementary/devices/index.html#devices. It doesn't appear to have been updated in a while (Since July 2018). A resource like this isn't very useful if it is not maintained.

There are also problems related to the implementation of Halium in Ubuntu Touch (https://github.com/ubports/ubuntu-touch/issues/404). They make it rather difficult to recommend someone new or just getting started to look at the in-progress port list.

If someone would like to add a link to the in-progress ports list to halium.org, the website is automatically rebuilt and deployed from here: https://github.com/Halium/halium.org. I'd also appreciate if they updated the ports-in-progress list, though.

**Comment by lduboeuf** [comment]
allright, i understand. This was just to avoid those questions we always have on Telegram groups where people ask if device xxx is ported. For newcomers, it is sometimes hard to find informations

**Comment by UniversalSuperBox** [comment]
In the UBports telegram group, the list of supported devices is in the channel description. The only way we could give any more information to people closer to where they are is by sending a welcome message immediately when they join. Even then I'm sure some wouldn't read it and they'd ask anyway. In a similar fashion, people ask if their weird laptops or desktops will work with Ubuntu. The expectation is that Linux runs on everything, we are an outlier in that sense.
